# Generated by Django 4.0.5 on 2022-07-14 19:16

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_usuario', models.CharField(max_length=40)),
                ('clave', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('correo_elec', models.EmailField(max_length=90)),
                ('fecha_nac', models.DateField()),
                ('nro_celular', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('codigo_postal', models.CharField(max_length=40)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=40)),
                ('marca_producto', models.CharField(max_length=40)),
                ('descripcion_producto', ckeditor.fields.RichTextField()),
                ('precio', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('fecha_creacion_producto', models.DateField()),
                ('fecha_actualiz', models.DateField()),
                ('responsable_carga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.usuario')),
            ],
        ),
    ]
